# Generated by Django 6.0.3 on 2026-03-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annee_actuelle',
            field=models.CharField(blank=True, help_text='Ex: L1, L2, L3, M1, M2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='compte_active',
            field=models.BooleanField(default=False, help_text="L'admin doit activer ce compte"),
        ),
        migrations.AddField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, help_text='Ex: Informatique, Génie Civil...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('alumni', 'Alumni')], default='etudiant', max_length=20),
        ),
    ]
