# Generated by Django 6.0.3 on 2026-03-14 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_annee_actuelle_profile_compte_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annee_licence',
            field=models.CharField(blank=True, help_text="Année d'obtention de la licence (ex: 2021)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='en_poste',
            field=models.BooleanField(default=False, help_text="Est-ce que l'alumni travaille actuellement ?"),
        ),
        migrations.AddField(
            model_name='profile',
            name='filiere_alumni',
            field=models.CharField(blank=True, help_text='Filière étudiée', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
