# Generated by Django 6.0.3 on 2026-03-15 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_message_favori_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annee_actuelle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annee_licence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='compte_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='en_poste',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere_alumni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offre', models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi'), ('cdi', 'CDI'), ('cdd', 'CDD'), ('alternance', 'Alternance'), ('freelance', 'Freelance')], default='stage', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('ville', models.CharField(default='Djibouti', max_length=100)),
                ('description', models.TextField()),
                ('niveau_requis', models.CharField(choices=[('tout', 'Tous niveaux'), ('licence', 'Licence (L1-L3)'), ('master', 'Master (M1-M2)'), ('doctorat', 'Doctorat'), ('bac', 'Bac')], default='tout', max_length=20)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('duree_stage', models.CharField(blank=True, help_text='Ex: 3 mois, 6 mois', max_length=50, null=True)),
                ('indemnite', models.CharField(blank=True, help_text='Ex: 50 000 DJF/mois', max_length=100, null=True)),
                ('salaire', models.CharField(blank=True, help_text='Ex: 150 000 DJF/mois', max_length=100, null=True)),
                ('experience_requise', models.CharField(blank=True, help_text='Ex: 2 ans minimum', max_length=100, null=True)),
                ('ecole_partenaire', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, help_text='Ex: 500 000 DJF', max_length=100, null=True)),
                ('delai', models.CharField(blank=True, help_text='Ex: 2 semaines', max_length=100, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
