# Generated by Django 6.0.3 on 2026-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_favorioffre_likeoffre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Publié')], default=0),
        ),
    ]
