# Generated by Django 6.0.3 on 2026-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='status',
            field=models.IntegerField(choices=[(0, 'En attente'), (1, 'Validée'), (2, 'Refusée')], default=0),
        ),
        migrations.AlterField(
            model_name='offre',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='delai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='duree_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='experience_requise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='indemnite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='salaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
