# Generated by Django 6.0.3 on 2026-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commentoffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promoted_from_etudiant',
            field=models.BooleanField(default=False),
        ),
    ]
